In [1]:
!pip install datacleaner

Collecting datacleaner
  Downloading datacleaner-0.1.5.tar.gz (6.5 kB)
  Preparing metadata (setup.py): started

WARNING: Ignoring invalid distribution -umpy (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\nour\anaconda3\lib\site-packages)
DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pandas in c:\users\nour\anaconda3\lib\site-packages (from datacleaner) (2.0.3)
Requirement already satisfied: scikit-learn in c:\users\nour\anaconda3\lib\site-packages (from datacleaner) (1.3.1)
Collecting update_checker (from datacleaner)
  Downloading update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nour\anaconda3\lib\site-packages (from pandas->datacleaner) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\nour\anaconda3\lib\site-packages (from pandas->datacleaner) (2020.1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\nour\anaconda3\lib\site-packages (from pandas->datacleaner) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in c:\users\nour\anaconda3\lib\site-packages (from pandas->datacleaner) (1.24.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\nour\anaconda3\lib\site-packages (from scikit-learn->datacleaner) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\nour\anaconda3\lib\site-packages (from scikit-learn->datacleaner) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\nour\anaconda3\lib\site-packages (from scikit-learn->datacleaner) (2.1.0)
Requirement already satisfied: requests>=2.3.0 in c:\users\nour\anaconda3\lib\site-packages (from update_checker->datacleaner) (2.31.0)
Requirement already satisfied: six>=1.5 in c:\users\nour\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datacleaner) (1.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nour\anaconda3\lib\site-packages (from requests>=2.3.0->update_checker->datacleaner) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nour\anaconda3\lib\site-packages (from requests>=2.3.0->update_checker->datacleaner) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nour\anaconda3\lib\site-packages (from requests>=2.3.0->update_checker->datacleaner) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nour\anaconda3\lib\site-packages (from requests>=2.3.0->update_checker->datacleaner) (2020.6.20)
Building wheels for collected packages: datacleaner
  Building wheel for datacleaner (setup.py): started
  Building wheel for datacleaner (setup.py): finished with status 'done'
  Created wheel for datacleaner: filename=datacleaner-0.1.5-py3-none-any.whl size=7420 sha256=7b33fa1fa75c4c25f3e4aa61df1ab15643a3b24a35c716cb805fd14172b82e1f
  Stored in directory: c:\users\nour\appdata\local\pip\cache\wheels\5f\22\1e\ad590d8c8f48adb030c6d9a1873fc4fe229649d513d7a36d18
Successfully built datacleaner
Installing collected packages: update_checker, datacleaner
Successfully installed datacleaner-0.1.5 update_checker-0.18.0

In [2]:
!pip install fasteda

Collecting fasteda
  Downloading fasteda-1.0.1.tar.gz (4.7 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pandas in c:\users\nour\anaconda3\lib\site-packages (from fasteda) (2.0.3)
Requirement already satisfied: numpy in c:\users\nour\anaconda3\lib\site-packages (from fasteda) (1.24.4)

WARNING: Ignoring invalid distribution -umpy (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\nour\anaconda3\lib\site-packages)
DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

Requirement already satisfied: matplotlib in c:\users\nour\anaconda3\lib\site-packages (from fasteda) (3.2.2)
Requirement already satisfied: seaborn in c:\users\nour\anaconda3\lib\site-packages (from fasteda) (0.12.2)
Collecting missingno (from fasteda)
  Downloading missingno-0.5.2-py3-none-any.whl (8.7 kB)
Requirement already satisfied: colorama in c:\users\nour\appdata\roaming\python\python38\site-packages (from fasteda) (0.4.6)
Requirement already satisfied: cycler>=0.10 in c:\users\nour\anaconda3\lib\site-packages (from matplotlib->fasteda) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\nour\anaconda3\lib\site-packages (from matplotlib->fasteda) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\nour\anaconda3\lib\site-packages (from matplotlib->fasteda) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\nour\anaconda3\lib\site-packages (from matplotlib->fasteda) (2.8.2)
Requirement already satisfied: scipy in c:\users\nour\anaconda3\lib\site-packages (from missingno->fasteda) (1.10.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\nour\anaconda3\lib\site-packages (from pandas->fasteda) (2020.1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\nour\anaconda3\lib\site-packages (from pandas->fasteda) (2023.3)
Requirement already satisfied: six in c:\users\nour\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib->fasteda) (1.15.0)
Building wheels for collected packages: fasteda
  Building wheel for fasteda (setup.py): started
  Building wheel for fasteda (setup.py): finished with status 'done'
  Created wheel for fasteda: filename=fasteda-1.0.1-py3-none-any.whl size=4739 sha256=196b8125b6fb45d1b0f3a5a3551c52d833a4fe30204450b79a5ed174bd34fdeb
  Stored in directory: c:\users\nour\appdata\local\pip\cache\wheels\16\a1\29\b9136342bd9faa9ea32da6994469fd8d9f3f390057b939a6e3
Successfully built fasteda
Installing collected packages: missingno, fasteda
Successfully installed fasteda-1.0.1 missingno-0.5.2

In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

import datacleaner
from datacleaner import autoclean
from fasteda import fast_eda

In [2]:
df = pd.read_csv("E:/NOUR/Documents/PFE/data/walmart-sales-dataset-of-45stores.csv")
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [3]:
df_clean = autoclean(df)
df_clean.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,19,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,52,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,85,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,118,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,20,1554806.68,0,46.50,2.625,211.350143,8.106

In [4]:
df_clean.isna().any()

Store           False
Date            False
Weekly_Sales    False
Holiday_Flag    False
Temperature     False
Fuel_Price      False
CPI             False
Unemployment    False
dtype: bool

In [5]:
import pymongo
from pymongo import MongoClient
con = pymongo.MongoClient("mongodb://localhost:27017/")
db = con.DCSTEC
collection = db.Sales

In [9]:
data = df_clean.to_dict(orient='records')
collection.insert_many(data)

In [8]:
fast_eda(df_clean)

DataFrame Head:

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,19,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,52,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,85,1611968.17,0,39.93,2.514,211.289143,8.106

DataFrame Tail:

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
6432,45,55,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,88,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,121,760281.43,0,58.85,3.882,192.308899,8.667

----------------------------------------------------------------------------------------------------
Missing values:

ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.

In [11]:
pip install --upgrade jinja2

Requirement already satisfied: jinja2 in c:\users\nour\anaconda3\lib\site-packages (2.11.2)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0 (from jinja2)
  Obtaining dependency information for MarkupSafe>=2.0 from https://files.pythonhosted.org/packages/74/a3/54fc60ee2da3ab6d68b1b2daf4897297c597840212ee126e68a4eb89fcd7/MarkupSafe-2.1.3-cp38-cp38-win_amd64.whl.metadata
  Downloading MarkupSafe-2.1.3-cp38-cp38-win_amd64.whl.metadata (3.1 kB)
Downloading MarkupSafe-2.1.3-cp38-cp38-win_amd64.whl (17 kB)
Installing collected packages: MarkupSafe, jinja2
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 1.1.1
    Uninstalling MarkupSafe-1.1.1:
      Successfully uninstalled MarkupSafe-1.1.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -umpy (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\nour\anaconda3\lib\site-packages)
DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
ERROR: Could not install packages due to an OSError: [WinError 5] Accès refusé: 'C:\\Users\\NOUR\\anaconda3\\Lib\\site-packages\\~arkupsafe\\_speedups.cp38-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

In [7]:
!pip install Jinja2

Requirement already satisfied: Jinja2 in c:\users\nour\anaconda3\lib\site-packages (2.11.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\nour\anaconda3\lib\site-packages (from Jinja2) (2.1.3)

WARNING: Ignoring invalid distribution -umpy (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\nour\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\nour\anaconda3\lib\site-packages)
DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063